### ISSUE TITLE
Minor fixes and improvements

### ISSUE THREAD

**Issue by pohlm01** [tweedegolf/101-rs#34]
## A1
- Slide 7 has a strange list
- Slide 8: Maybe don't use the embedded link to display on the slide
- Slide 30: I find it a bit counterintuitive that the first bullet point after the heading “Statements” explains what an Expression is. Maybe move the first bullet point to the next slide, where expressions are explained anyway
- Slide 34: The light font on the image is hard to read (As I found out later, this is apparently only a problem in the dark mode. If you don't use that, you can probably ignore this)

### 1.0 - Installation
- This link gives a 404: https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-pack
- The following link is not clickable: https://www.youtube.com/playlist?list=PLg7s6cbtAD15G8lNyoaYDuKZSKyJrgwB-
- “To clone the repository, you'll need an account on GitHub” is not true. As long as only pull but not push, you don't need one (though I agree that it is helpful anyway)

### 2.1
- In the end, you say that `exercises/A1/2-move-semantics/01.rs` should compile as is, but this is not true, as there is one `mut` missing.
- You may want to delete `exercises/A1/2-move-semantics/src/main.rs`

## A2
- Slide 21: In the subheading, you probably mean 'Structs' instead of 'Enums'? 

- exercises/A2/4-boxed-data/src/main.rs:102 “If you have time let” should be “If you have time left”
- exercises/A2/4-boxed-data/src/main.rs uses a different syntax ('///') instead of ('//') to explain the exercise

## 3.B
- https://101-rs.tweede.golf/B-application-programming/mod.html previous to last line: 'allications' should be 'allocations'

**Comment by hdoordt** [comment]
Hi @pohlm01! Thank you for having a look at the repo contents. Could I persuade you to open a PR with the fixes?
