### ISSUE TITLE
Invite students for test lecture

### ISSUE THREAD

**Issue by erikjee** [tweedegolf/101-rs#6]

**Comment by bvgastel** [comment]
I can help with this one.

**Comment by bvgastel** [comment]
Maybe even in a real lecture hall on campus?

**Comment by erikjee** [comment]
That would be great!

We prefer doing it at TG's office and having a small (5-10) group, to keep it simple the first time and get some qualitative feedback. PS It will be a lecture + exercise. @LisetRoos will contact you with details soon.

**Comment by hdoordt** [comment]
@LisetRoos This issue can be closed, right?
