### ISSUE TITLE
Decide on quiz platform

### ISSUE THREAD

**Issue by LisetRoos** [tweedegolf/101-rs#8]
- **Nearpod** (gratis basisversie, veel mogelijkheden, o.a. gamified en integratie met je slides)
- Kahoot (gratis basisversie, gamified, kinderlijk?)
- Socrative ($179.99 USD/year, even navragen of ze dat bij Bratislava al gebruiken, mss kun je een account krijgen)
- Forms (zal bij het pakket van de uni van Bratislava zitten, als ze ook Teams gebruiken. Voordeel is dat studenten dan automatisch ingelogd zijn en je het makkelijk in een voor hun bekende omgeving kunt integreren. Nadeel is dat antwoorden van open vragen visueel slecht weergegeven worden)

**Comment by bvgastel** [comment]
Mentimeter wordt soms ook gebruikt.

**Comment by hdoordt** [comment]
Thanks @LisetRoos @bvgastel !

I'm digging Nearpod, and will probably go for that platform.

However, in this repo we can just provide the questions (and maybe answers?) with the lecture slides in text format. Then users of the content can copy&paste the quiz questions into their own tool

**Comment by bvgastel** [comment]
That is probably the best idea, to keep the questions in this repo.
