### ISSUE TITLE
101-rs/slides / D-trait-objects-patterns.md : Typestate: example : typo ? 

### ISSUE THREAD

**Issue by duron-rik** [tweedegolf/101-rs#82]
impl CoffeeMachine<ItemSelected> {
    fn insert_money(self) -> CoffeeMachine<MoneyInserted> {
        println!("Money inserted!");
        self.insert_money()
    }
}

=> self.into_state() instead of self.insert_money() to prevent recursion

**Comment by hdoordt** [comment]
Good find, thanks!
